
export const SET_LOADING = "SET_LOADING";
export const SET_FOLLOWER_LOADING = "SET_FOLLOWER_LOADING";
export const SET_BUTTON_LOADING = "SET_BUTTON_LOADING";
export const SET_USER_STATE = "SET_USER_STATE";
export const SAVE_USER_STATE = "SAVE_USER_STATE";
export const SAVE_USER_STATE_RESPONSE = "SAVE_USER_STATE_RESPONSE";

export const USER_LOGOUT_STATE = "USER_LOGOUT_STATE";
export const USER_LOGOUT_RESPONSE = "USER_LOGOUT_RESPONSE";

export const DELETE_ACCOUNT_STATE = "DELETE_ACCOUNT_STATE";
export const DELETE_ACCOUNT_RESPONSE = "DELETE_ACCOUNT_RESPONSE";

export const GET_PROFILE_STATE = "GET_PROFILE_STATE";
export const GET_PROFILE_STATE_RESPONSE = "GET_PROFILE_STATE_RESPONSE";

export const USER_LOGIN_STATE = "USER_LOGIN_STATE";
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE";

export const GET_PROFILE_VIEWERS = "GET_PROFILE_VIEWERS";
export const GET_PROFILE_VIEWERS_RESPONSE = "GET_PROFILE_VIEWERS_RESPONSE";

export const VERIFY_OTP_STATE = "VERIFY_OTP_STATE";
export const VERIFY_OTP_RESPONSE = "VERIFY_OTP_RESPONSE";

export const FORGET_PASSWORD_STATE = "FORGET_PASSWORD_STATE";
export const FORGET_PASSWORD_RESPONSE = "FORGET_PASSWORD_RESPONSE";

export const RESET_PASSWORD_STATE = "RESET_PASSWORD_STATE";
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE";

export const GET_USER_STATE = "GET_USER_STATE";
export const GET_USER_STATE_RESPONSE = "GET_USER_STATE_RESPONSE";

export const SEND_REQUEST_STATE = "SEND_REQUEST_STATE";
export const SEND_REQUEST_STATE_RESPONSE = "SEND_REQUEST_STATE_RESPONSE";

export const SET_REQUEST_STATE = "SET_REQUEST_STATE";
export const GET_REQUEST_STATE = "GET_REQUEST_STATE";
export const GET_REQUEST_STATE_RESPONSE = "GET_REQUEST_STATE_RESPONSE";

export const GET_FOLLOWERS_STATE = "GET_FOLLOWERS_STATE";
export const GET_FOLLOWERS_STATE_RESPONSE = "GET_FOLLOWERS_STATE_RESPONSE";

export const REMOVE_FOLLOWER_STATE = "REMOVE_FOLLOWER_STATE";
export const REMOVE_FOLLOWER_RESPONSE = "REMOVE_FOLLOWER_RESPONSE";

export const BLOCK_USER_STATE = "BLOCK_USER_STATE";
export const BLOCK_USER_RESPONSE = "BLOCK_USER_RESPONSE";

export const UPDATE_REQUEST_STATE = "UPDATE_REQUEST_STATE";
export const UPDATE_REQUEST_RESPONSE = "UPDATE_REQUEST_RESPONSE";

export const SET_POST_LOADING = "SET_POST_LOADING";
export const SET_POST_STATE = "SET_POST_STATE";
export const SET_POST_RESPONSE = "SET_POST_RESPONSE";

export const GET_POST_STATE = "GET_POST_STATE";
export const GET_POST_RESPONSE = "GET_POST_RESPONSE";

export const GET_MENTION_POST = "GET_MENTION_POST";
export const GET_MENTION_POST_RESPONSE = "GET_MENTION_POST_RESPONSE";

export const SET_POST_LIKE_STATE = "SET_POST_LIKE_STATE";
export const SET_POST_LIKE_RESPONSE = "SET_POST_LIKE_RESPONSE";

export const DELETE_POST_STATE = "DELETE_POST_STATE";
export const DELETE_POST_RESPONSE = "DELETE_POST_RESPONSE";

export const SET_COMMENT_STATE = "SET_COMMENT_STATE";
export const SET_COMMENT_RESPONSE = "SET_COMMENT_RESPONSE";
export const GET_COMMENT_STATE = "GET_COMMENT_STATE";
export const GET_COMMENT_RESPONSE = "GET_COMMENT_RESPONSE";

export const GET_LIKES_COMMENTS_STATE = "GET_LIKES_COMMENTS_STATE";
export const GET_LIKES_COMMENTS_RESPONSE = "GET_LIKES_COMMENTS_RESPONSE";

export const SAVE_POST_STATE = "SAVE_POST_STATE";
export const SAVE_POST_RESPONSE = "SAVE_POST_RESPONSE";

export const SET_SETTING_STATE = 'SET_SETTING_STATE';
export const SET_SETTING_STATE_SUCCESS = 'SET_SETTING_STATE_SUCCESS';
export const SET_SETTING_STATE_FAILURE = 'SET_SETTING_STATE_FAILURE';

export const SET_USER_STATUS = 'SET_USER_STATUS';
export const SET_USER_STATUS_RESPONSE = 'SET_USER_STATUS_RESPONSE';

export const SET_VISITOR_TIME = "SET_VISITOR_TIME";
export const SET_VISITOR_TIME_SUCCESS = "SET_VISITOR_TIME_SUCCESS";
export const SET_VISITOR_TIME_FAILURE = "SET_VISITOR_TIME_FAILURE";

export const GET_DAILY_USAGES = 'GET_DAILY_USAGES';
export const GET_DAILY_USAGES_SUCCESS = 'GET_DAILY_USAGES_SUCCESS';
export const GET_DAILY_USAGES_FAILURE = 'GET_DAILY_USAGES_FAILURE';

export const DELETE_FILES_FROM_CLOUDIANRY_RESPONSE = 'DELETE_FILES_FROM_CLOUDIANRY_RESPONSE';
export const DELETE_FILES_FROM_CLOUDIANRY_STATE = 'DELETE_FILES_FROM_CLOUDIANRY_STATE';

export const CREATE_STORIES_STATE_RESPONSE = "CREATE_STORIES_STATE_RESPONSE";
export const CREATE_STORIES_STATE = "CREATE_STORIES_STATE";

export const GET_STORIES_STATE = 'GET_STORIES_STATE';
export const GET_STORIES_STATE_RESPONSE = 'GET_STORIES_STATE_RESPONSE'
