
export const SET_LOADING = "SET_LOADING";
export const SET_BUTTON_LOADING = "SET_BUTTON_LOADING";
export const SET_USER_STATE = "SET_USER_STATE";
export const SAVE_USER_STATE = "SAVE_USER_STATE";
export const SAVE_USER_STATE_SUCCESS = "SAVE_USER_STATE_SUCCESS";
export const SAVE_USER_STATE_FAILURE = "SAVE_USER_STATE_FAILURE";

export const UPDATE_USER_STATE = "UPDATE_USER_STATE";
export const UPDATE_USER_STATE_SUCCESS = "UPDATE_USER_STATE_SUCCESS";
export const UPDATE_USER_STATE_FAILURE = "UPDATE_USER_STATE_FAILURE";

export const USER_LOGOUT_STATE = "USER_LOGOUT_STATE";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const DELETE_ACCOUNT_STATE = "DELETE_ACCOUNT_STATE";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";

export const GET_PROFILE_STATE = "GET_PROFILE_STATE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_STATE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_STATE_FAILURE";

export const USER_LOGIN_STATE = "USER_LOGIN_STATE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const GET_PROFILE_VIEWERS = "GET_PROFILE_VIEWERS";
export const GET_PROFILE_VIEWERS_SUCCESS = "GET_PROFILE_VIEWERS_SUCCESS";
export const GET_PROFILE_VIEWERS_FAILURE = "GET_PROFILE_VIEWERS_FAILURE";

export const VERIFY_OTP_STATE = "VERIFY_OTP_STATE";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const FORGET_PASSWORD_STATE = "FORGET_PASSWORD_STATE";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILURE = "FORGET_PASSWORD_FAILURE";


export const RESET_PASSWORD_STATE = "RESET_PASSWORD_STATE";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const GET_USER_STATE = "GET_USER_STATE";
export const GET_USER_STATE_SUCCESS = "GET_USER_STATE_SUCCESS";
export const GET_USER_STATE_FAILURE = "GET_USER_STATE_FAILURE";

export const SEND_REQUEST_STATE = "SEND_REQUEST_STATE";
export const SEND_REQUEST_STATE_SUCCESS = "SEND_REQUEST_STATE_SUCCESS";
export const SEND_REQUEST_STATE_FAILURE = "SEND_REQUEST_STATE_FAILURE";

export const SET_REQUEST_STATE = "SET_REQUEST_STATE";
export const GET_REQUEST_STATE = "GET_REQUEST_STATE";
export const GET_REQUEST_STATE_SUCCESS = "GET_REQUEST_STATE_SUCCESS";
export const GET_REQUEST_STATE_FAILURE = "GET_REQUEST_STATE_FAILURE";

export const GET_FOLLOWERS_STATE = "GET_FOLLOWERS_STATE";
export const GET_FOLLOWERS_STATE_SUCCESS = "GET_FOLLOWERS_STATE_SUCCESS";
export const GET_FOLLOWERS_STATE_FAILURE = "GET_FOLLOWERS_STATE_FAILURE";

export const REMOVE_FOLLOWER_STATE = "REMOVE_FOLLOWER_STATE";
export const REMOVE_FOLLOWER_STATE_SUCCESS = "REMOVE_FOLLOWER_STATE_SUCCESS";
export const REMOVE_FOLLOWER_STATE_FAILURE = "REMOVE_FOLLOWER_STATE_FAILURE";

export const UPDATE_REQUEST_STATE = "UPDATE_REQUEST_STATE";
export const UPDATE_REQUEST_STATE_SUCCESS = "UPDATE_REQUEST_STATE_SUCCESS";
export const UPDATE_REQUEST_STATE_FAILURE = "UPDATE_REQUEST_STATE_FAILURE";

export const SET_POST_LOADING = "SET_POST_LOADING";
export const SET_POST_STATE = "SET_POST_STATE";
export const SET_POST_STATE_SUCCESS = "SET_POST_STATE_SUCCESS";
export const SET_POST_STATE_FAILURE = "SET_POST_STATE_FAILURE";

export const GET_POST_STATE = "GET_POST_STATE";
export const GET_POST_STATE_SUCCESS = "GET_POST_STATE_SUCCESS";
export const GET_POST_STATE_FAILURE = "GET_POST_STATE_FAILURE";

export const GET_MENTION_POST = "GET_MENTION_POST";
export const GET_MENTION_POST_SUCCESS = "GET_POST_STATE_SUCCESS";
export const GET_MENTION_POST_FAILURE = "GET_POST_STATE_FAILURE";

export const SET_POST_LIKE_STATE = "SET_POST_LIKE_STATE";
export const SET_POST_LIKE_STATE_SUCCESS = "SET_POST_LIKE_STATE_SUCCESS";
export const SET_POST_LIKE_STATE_FAILURE = "SET_POST_LIKE_STATE_FAILURE";

export const SET_COMMENT_STATE = "SET_COMMENT_STATE";
export const SET_COMMENT_STATE_SUCCESS = "SET_COMMENT_STATE_SUCCESS";
export const SET_COMMENT_STATE_FAILURE = "SET_COMMENT_STATE_FAILURE";
export const GET_COMMENT_STATE = "GET_COMMENT_STATE";
export const GET_COMMENT_STATE_SUCCESS = "GET_COMMENT_STATE_SUCCESS";
export const GET_COMMENT_STATE_FAILURE = "GET_COMMENT_STATE_FAILURE";

export const GET_LIKE_STATE = "GET_LIKE_STATE";
export const GET_LIKE_STATE_SUCCESS = "GET_LIKE_STATE_SUCCESS";
export const GET_LIKE_STATE_FAILURE = "GET_LIKE_STATE_FAILURE";
